# Generated by Django 4.1.6 on 2023-03-10 01:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Categories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Food_Categories', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mackup_Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('Artist_image', models.ImageField(upload_to='MackupArtist')),
                ('mobile', models.CharField(max_length=12)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mehndi_Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('Artist_image', models.ImageField(upload_to='MehndiArtist')),
                ('mobile', models.CharField(max_length=12)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Photographers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='Photographer')),
                ('mobile', models.CharField(max_length=12)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue_Type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('venue_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venue_Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=50)),
                ('venue_image', models.ImageField(upload_to='VenueImage')),
                ('mobile', models.CharField(max_length=12)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
                ('veg_price', models.IntegerField()),
                ('nonveg_price', models.IntegerField()),
                ('room_availability', models.IntegerField()),
                ('Venue_Type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Tables.venue_type')),
            ],
        ),
        migrations.CreateModel(
            name='Photographer_works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_images', models.ImageField(upload_to='Photographer_work')),
                ('photographer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tables.photographers')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Suplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('food_image', models.ImageField(upload_to='VenueImage')),
                ('mobile', models.CharField(max_length=12)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
                ('Food_Categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.food_categories')),
            ],
        ),
    ]
